### PR TITLE
change style property and added . at assets

### LINKED ISSUE #7: Bug on mobile view

### PR DESCRIPTION
**Pull request by schmelto**
resolve #7 
further resolve issue with new asset folder structure

Before:
image

mobile view now:
image

### CODE REVIEW

**Comment by rohan-kulkarni-25** [comment]
Please deploy your version so we can check the changes

**Review by rohan-kulkarni-25 — CHANGES_REQUESTED** [review]
Please deploy the webstie on git hub pages

**Comment by schmelto** [comment]
> Please deploy the webstie on git hub pages

https://schmelto.github.io/EddieHub_Members/ @rohank2502

**Comment by schmelto** [comment]
think this also resolve #10

**Review by adityaraute — APPROVED** [review]

**Review by rohan-kulkarni-25 — COMMENTED** [review]
Lol i forgot the .

**Pull request merged**
